# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker build -t vnoel/app-curie:latest docker
    - docker push vnoel/app-curie:latest

test:
  stage: test
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker pull vnoel/app-curie:latest
    - docker run --name app-curie -v ${PWD}:/appCurie -d vnoel/app-curie:latest
    - docker exec -t app-curie bash -c "cd /appCurie; python manage.py test -v 3 --settings=AppCurie.test_settings"
