# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - apk add docker-compose --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
  - docker-compose -v

build-dev:
  stage: build
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker-compose build app-curie-dev
    - docker tag app-curie-dev:latest vnoel/app-curie-dev:latest
#    - docker push vnoel/app-curie-dev:latest

build-test:
  stage: build
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker-compose build app-curie-test
    - docker tag app-curie-test:latest vnoel/app-curie-test:latest
    - docker push vnoel/app-curie-test:latest

build-prod:
  stage: build
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker-compose build app-curie
    - docker tag app-curie:latest vnoel/app-curie:latest
    - docker push vnoel/app-curie:latest

test:
  stage: test
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker pull vnoel/app-curie-test:latest
    - docker tag vnoel/app-curie-test:latest app-curie-test:latest
    - docker-compose up -d app-curie-test app-curie-db
    - docker exec -u www-data -t app-curie /bin/bash -c "sleep 10"
    - docker exec -u www-data -t app-curie /bin/bash /appCurie/create_default_db.sh --settings=settings.test_settings
    - docker exec -u www-data -t app-curie /bin/bash /appCurie/create_default_admin.sh  --settings=settings.test_settings
    - docker exec -u www-data -t app-curie python manage.py test api -v 2 --settings=settings.test_settings