# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache py2-pip
  - pip install docker-compose
  - docker-compose -v

build:
  stage: build
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker-compose build app-curie-test
    - docker push vnoel/app-curie:latest

test:
  stage: test
  script:
    - docker login -u vnoel -p $DOCKERHUB_PASSWORD
    - docker pull vnoel/app-curie:latest
    - docker-compose up -d app-curie-test
    - docker exec -t app-curie yarn
    - docker exec -t app-curie npm run dev
    - docker exec -t app-curie python manage.py test -v 3 --settings=AppCurie.test_settings
