image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - apk add docker-compose --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
  - docker-compose -v
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin


build-dev:
  stage: build
  script:
    - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build webmaboss-dev
    - docker tag webmaboss-dev registry.gitlab.com/vincent.noel/webmaboss:dev
    - docker push registry.gitlab.com/vincent.noel/webmaboss:dev

build-test:
  stage: build
  script:
    - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build webmaboss-test
    - docker tag webmaboss-test registry.gitlab.com/vincent.noel/webmaboss:test
    - docker push registry.gitlab.com/vincent.noel/webmaboss:test

build-prod:
  stage: build
  script:
    - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build webmaboss
    - docker tag webmaboss registry.gitlab.com/vincent.noel/webmaboss
    - docker push registry.gitlab.com/vincent.noel/webmaboss
    - docker tag webmaboss vnoel/webmaboss
    - docker push vnoel/webmaboss

test-api:
  stage: test
  script:
    - docker pull registry.gitlab.com/vincent.noel/webmaboss:test
    - docker tag registry.gitlab.com/vincent.noel/webmaboss:test webmaboss-test:latest
    - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d webmaboss-test
    - docker exec -u www-data -t webmaboss-test /bin/bash -c "sleep 30"
    - docker exec -u www-data -t webmaboss-test /bin/bash /var/webmaboss/create_default_db.sh --settings=settings.test_settings
    - docker exec -u www-data -t webmaboss-test /bin/bash /var/webmaboss/create_default_admin.sh  --settings=settings.test_settings
    - docker exec -u www-data -t webmaboss-test python manage.py test api -v 2 --settings=settings.test_settings

test-frontend:
  stage: test
  script:
    - docker pull registry.gitlab.com/vincent.noel/webmaboss:test
    - docker tag registry.gitlab.com/vincent.noel/webmaboss:test webmaboss-test:latest
    - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d webmaboss-test
    - docker exec -u www-data -t webmaboss-test /bin/bash -c "sleep 30"
    - docker exec -u www-data -t webmaboss-test /bin/bash /var/webmaboss/create_default_db.sh --settings=settings.test_settings
    - docker exec -u www-data -t webmaboss-test /bin/bash /var/webmaboss/create_default_admin.sh  --settings=settings.test_settings
    - docker exec -u www-data -t webmaboss-test python manage.py test frontend -v 2 --settings=settings.test_settings