# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - apk add docker-compose --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
  - docker-compose -v
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY


build-dev:
  stage: build
  script:
#    - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin
    - docker-compose build app-curie-dev
    - docker tag app-curie-dev registry.gitlab.com/vincent.noel/appcurie:dev
    - docker push registry.gitlab.com/vincent.noel/appcurie:dev

build-test:
  stage: build
  script:
#    - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin
    - docker-compose build app-curie-test
    - docker tag app-curie-test registry.gitlab.com/vincent.noel/appcurie:test
    - docker push registry.gitlab.com/vincent.noel/appcurie:test

build-prod:
  stage: build
  script:
#    - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin
    - docker-compose build app-curie
    - docker tag app-curie registry.gitlab.com/vincent.noel/appcurie
    - docker push registry.gitlab.com/vincent.noel/appcurie
#    - docker push vnoel/webmaboss:latest

test-api:
  stage: test
  script:
#    - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin
    - docker pull registry.gitlab.com/vincent.noel/appcurie:test
    - docker tag registry.gitlab.com/vincent.noel/appcurie:test app-curie-test:latest
    - docker-compose up -d app-curie-test app-curie-db
    - docker exec -u www-data -t app-curie-test /bin/bash -c "sleep 10"
    - docker exec -u www-data -t app-curie-test /bin/bash /appCurie/create_default_db.sh --settings=settings.test_settings
    - docker exec -u www-data -t app-curie-test /bin/bash /appCurie/create_default_admin.sh  --settings=settings.test_settings
    - docker exec -u www-data -t app-curie-test python manage.py test api -v 2 --settings=settings.test_settings

test-frontend:
  stage: test
  script:
#    - echo "$DOCKERHUB_PASSWORD" | docker login -u vnoel --password-stdin
    - docker pull registry.gitlab.com/vincent.noel/appcurie:test
    - docker tag registry.gitlab.com/vincent.noel/appcurie:test app-curie-test:latest
    - docker-compose up -d app-curie-test
    - docker exec -u www-data -t app-curie-test /bin/bash -c "sleep 10"
    - docker exec -u www-data -t app-curie-test /bin/bash /appCurie/create_default_db.sh --settings=settings.test_settings
    - docker exec -u www-data -t app-curie-test /bin/bash /appCurie/create_default_admin.sh  --settings=settings.test_settings
    - docker exec -u www-data -t app-curie-test python manage.py test frontend -v 2 --settings=settings.test_settings