#docker-compose.yml
version: '3.3'
services:

  app-curie:
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile

    image: app-curie
    container_name: app-curie
    volumes:
      - app-curie-data:/appCurie/data
    ports:
      - "8000:8000"
    user: www-data

  app-curie-dev:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile

    image: app-curie-dev
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8889:8888"
    user: user
    volumes:
      - .:/appCurie

    restart: unless-stopped

  app-curie-test:
    build:
      context: ./
      dockerfile: docker/tests/Dockerfile

    image: app-curie-test:latest
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8888:8888"
    user: user
    volumes:
      - .:/appCurie

    restart: unless-stopped

volumes:
  app-curie-data:
