#docker-compose.yml
version: '3.3'
services:

  app-curie:
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile

    image: app-curie
    container_name: app-curie
    volumes:
      - data:/appCurie/data
    ports:
      - "8000:8000"
    user: www-data
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=app-curie-db
      - DB_PORT=3306

  app-curie-dev:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile

    image: app-curie-dev
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8889:8888"
    user: user
    volumes:
      - .:/appCurie
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=app-curie-db
      - DB_PORT=3306
    restart: unless-stopped

  app-curie-test:
    build:
      context: ./
      dockerfile: docker/tests/Dockerfile

    image: app-curie-test:latest
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8888:8888"
    user: user
    volumes:
      - .:/appCurie
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=app-curie-db
      - DB_PORT=3306
    restart: unless-stopped

  app-curie-db:
    image: mariadb
    container_name: app-curie-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db:
  data:
