#docker-compose.yml
version: '3.4'
services:

  webmaboss-db:
    image: mariadb:11.3.2
    container_name: webmaboss-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    command: --max_allowed_packet=268435456      # Set max_allowed_packet to 256M (or any other value)
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=webmaboss
      - MYSQL_USER=webmaboss
      - MYSQL_PASSWORD=InsertAPassWordForTheDatabase

  webmaboss:
    build:
      context: ./
      dockerfile: docker/Dockerfile

    image: sysbiocurie/webmaboss:1.0.4
    container_name: webmaboss
    volumes:
      - data:/var/webmaboss/data
    ports:
      - "8000:8000"
    user: www-data
    environment:
      - DB_NAME=webmaboss
      - DB_USER=webmaboss
      - DB_PASSWORD=InsertAPassWordForTheDatabase
      - DB_HOST=webmaboss-db
      - DB_PORT=3306

    depends_on:
      - webmaboss-db

    restart: unless-stopped

volumes:
  db:
  data:
