#docker-compose.yml
version: '3.4'
services:

  webmaboss-db:
    image: mariadb:10.5.4
    container_name: webmaboss-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=webmaboss
      - MYSQL_USER=webmaboss
      - MYSQL_PASSWORD=J4*wxQ5sd7F79ZpHHP8*%J#e

  webmaboss:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: webmaboss

    image: webmaboss
    container_name: webmaboss
    volumes:
      - data:/var/webmaboss/data
    ports:
      - "8000:8000"
    user: www-data
    environment:
      - DB_NAME=webmaboss
      - DB_USER=webmaboss
      - DB_PASSWORD=J4*wxQ5sd7F79ZpHHP8*%J#e
      - DB_HOST=webmaboss-db
      - DB_PORT=3306

    depends_on:
      - webmaboss-db

  webmaboss-dev:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: webmaboss-dev

    image: webmaboss-dev
    container_name: webmaboss-dev
    ports:
      - "8000:8000"

    volumes:
      - .:/var/webmaboss
    environment:
      - DB_NAME=webmaboss
      - DB_USER=webmaboss
      - DB_PASSWORD=J4*wxQ5sd7F79ZpHHP8*%J#e
      - DB_HOST=webmaboss-db
      - DB_PORT=3306

    depends_on:
      - webmaboss-db

    restart: unless-stopped

  webmaboss-test:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      target: webmaboss-test

    image: webmaboss-test:latest
    container_name: webmaboss-test
    ports:
      - "8000:8000"
      - "8888:8888"
    user: www-data
    volumes:
      - data:/var/webmaboss/data
    environment:
      - DB_NAME=webmaboss
      - DB_USER=webmaboss
      - DB_PASSWORD=J4*wxQ5sd7F79ZpHHP8*%J#e
      - DB_HOST=webmaboss-db
      - DB_PORT=3306

    depends_on:
      - webmaboss-db

    restart: unless-stopped


volumes:
  db:
  data:
