#docker-compose.yml
version: '3.3'
services:

  app-curie:
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile

    image: app-curie
    container_name: app-curie
    ports:
      - "8000:8000"
    user: www-data

  app-curie-dev:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile

    image: app-curie-dev
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8888:8888"
    user: user
    volumes:
      - /home/labestiol/Work/code/AppCurie:/appCurie
      - /home/labestiol/Work/code/GINsim-python/ginsim:/opt/conda/lib/python3.6/site-packages/ginsim
      - /home/labestiol/Work/code/GINsim-python/biolqm:/opt/conda/lib/python3.6/site-packages/biolqm
      - /home/labestiol/Work/code/pyMaBoSS/maboss:/opt/conda/lib/python3.6/site-packages/maboss

    restart: unless-stopped

  app-curie-test:
    build:
      context: ./
      dockerfile: docker/tests/Dockerfile

    image: vnoel/app-curie:latest
    container_name: app-curie
    ports:
      - "8000:8000"
      - "8888:8888"
    user: user
    volumes:
      - ${PWD}:/appCurie

    restart: unless-stopped
